nav:
  - 首页:
      - README.md
      - introduction.md
      - quickstart.md
      - libraries.md
      - models.md
      - tutorials.md
      - data-usage-policies.md
      - usage-policies.md
  - 引导:
      - guides/index.md
      - guides/completion.md
      - guides/editing-code.md
      - guides/chat.md
      - guides/images.md
      - guides/fine-tuning.md
      - guides/embedding.md
      - guides/speech-to-text.md
      - guides/moderation.md
      - guides/rate-limits.md
      - guides/error-codes.md
      - guides/safety-best-practices.md
      - guides/production-best-practices.md
  - API:
      - api-reference/index.md
      - api-reference/introduction.md
      - api-reference/authentication.md
      - api-reference/making-requests.md
      - api-reference/models.md
      - api-reference/completions.md
      - api-reference/chat.md
      - api-reference/edits.md
      - api-reference/images.md
      - api-reference/embeddings.md
      - api-reference/audio.md
      - api-reference/files.md
      - api-reference/fine-tunes.md
      - api-reference/moderations.md
      - api-reference/engines.md
      - api-reference/parameter-details.md
  - 价格:
      - price.md
  - 工具:
      - prompts.md
      - tags.md
